# Add networks to an existing instance
#

- name: idr vm | get openstack servers
  os_server_facts:
  always_run: yes

- name: idr vm | get openstack networks
  os_networks_facts:
  always_run: yes

- name: idr vm | debug server
  debug:
    msg: "{{ idr_instance_network_server }}"
    verbosity: 1

- name: idr vm | debug server networks
  debug:
    msg: >
      {{
        (openstack_servers |
          selectattr(idr_instance_network_server_key, "equalto", idr_instance_network_server) |
          first |
          default( {'networks': []} ))
        .networks
      }}
    verbosity: 1

- name: idr vm | debug required networks
  debug:
    msg: >
      {{ (openstack_networks | selectattr("name", "equalto", item) | list)
      }}
    verbosity: 1
  with_items:
  - "{{ idr_instance_network_networks }}"

- name: idr vm | attach instance to network
  command: >
    nova interface-attach
      --net-id {{ (openstack_networks |
        selectattr("name", "equalto", item) | list).0.id }}
      {{ idr_instance_network_server }}
  when: >
    item not in (
      (openstack_servers |
        selectattr(idr_instance_network_server_key, "equalto", idr_instance_network_server) |
        first |
        default( {'networks': []} ))
      .networks
    )
  with_items:
  - "{{ idr_instance_network_networks }}"
